language: cpp
install:
    - cd ..
    - wget https://transfer.sh/2wk8V/crosscompiler.tar.xz
    - tar -xvf crosscompiler.tar.xz
    - cd -
    - sudo apt-get install grub2 grub2-common

before_install:
    - openssl aes-256-cbc -K $encrypted_43d224ccb4ae_key -iv $encrypted_43d224ccb4ae_iv -in id_rsa.enc -out ci/id_rsa -d

script:
    - eval "$(ssh-agent -s)" #start the ssh agent
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - git clone ssh://travis@dark32.cf:2222/home/travis/mtgos-builds
    - cd ..
    - export PATH=$HOME/opt/bin:$PATH
    - echo "Building for i686"
    - cp templates/i686 config.yaml
    - sed -i 's/finished: false/finished: true/' config.yaml
    - ./make.py --clean
    - cp bootloader/3ds/arm9loaderhax_si.bin mtgos-builds/arm9loaderhax_si.bin
    - mv bootable.iso mtgos-builds/i686.iso
    - echo "Building for x86_64"
    - cp templates/x86_64 config.yaml
    - sed -i 's/finished: false/finished: true/' config.yaml
    - ./make.py --clean
    - mv bootable.iso mtgos-builds/x86_64.iso
    - echo "Building for 3DS"
    - cp templates/3ds9 config.yaml
    - sed -i 's/finished: false/finished: true/' config.yaml
    - ./make.py --clean
    - mv mtgos.elf mtgos-builds/kernel9.elf
    - cp templates/3ds11 config.yaml
    - sed -i 's/finished: false/finished: true/' config.yaml
    - ./make.py --clean
    - mv mtgos.elf mtgos-builds/kernel11.elf
after_success:
    - cd mtgos-builds
    - git add .
    - git commit -am 'Autogenerated build'
    - git push origin master
