language: python
install:
    - cd ~
    - wget http://dark32.cf/static/crosscompiler.tar.xz
    - tar -xf crosscompiler.tar.xz
    - cd -
    - yes '' | sudo add-apt-repository ppa:fkrull/deadsnakes
    - sudo apt-get update
    - sudo apt-get install grub2 grub2-common python3.4 xorriso
    - wget https://bootstrap.pypa.io/get-pip.py
    - sudo python3.4 get-pip.py
    - python3.4 -m pip install pyyaml
python:
    - "3.4"
before_install:
    - openssl aes-256-cbc -K $encrypted_43d224ccb4ae_key -iv $encrypted_43d224ccb4ae_iv -in id_rsa.enc -out ci/id_rsa -d

script:
    - eval "$(ssh-agent -s)" #start the ssh agent
    - chmod 600 ci/id_rsa
    - ssh-add ci/id_rsa
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - git clone ssh://travis@dark32.cf:2222/home/travis/mtgos-builds
    - export PATH=$HOME/opt/bin:$PATH
    - cp font.bin mtgos-builds
    - echo "Building for i686"
    - cp templates/i686.yaml config.yaml
    - python3.4 ./make.py --clean --ci
    - mv bootable.iso mtgos-builds/i686.iso
    - echo "Building for x86_64"
    - cp templates/x86_64.yaml config.yaml
    - python3.4  ./make.py --clean --ci
    - mv bootable.iso mtgos-builds/x86_64.iso
    - echo "Building for 3DS"
    - cp bootloader/3ds/arm9loaderhax_si.bin mtgos-builds/arm9loaderhax_si.bin
    - cp templates/3ds9.yaml config.yaml
    - python3.4  ./make.py --clean --ci
    - mv mtgos.elf mtgos-builds/kernel9.elf
    - cp templates/3ds11.yaml config.yaml
    - python3.4 ./make.py --clean --ci
    - mv mtgos.elf mtgos-builds/kernel11.elf
after_success:
    - cd mtgos-builds
    - git add .
    - git config --global user.email "morten@dark32.cf"
    - git config --global user.name "Travis CI"
    - git branch $TRAVIS_BRANCH
    - git commit -am "Autogenerated build - $TRAVIS_COMMIT"
    - git push origin $TRAVIS_BRANCH
